-- MySQL Script generated by MySQL Workbench
-- 10/11/17 15:19:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema furniture
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema furniture
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `furniture` DEFAULT CHARACTER SET utf8 ;
USE `furniture` ;

-- -----------------------------------------------------
-- Table `furniture`.`PV_CATEGORIA_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_CATEGORIA_USUARIO` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `furniture`.`PV_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_CLIENTE` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NULL,
  `ap_paterno_cliente` VARCHAR(45) NULL,
  `ap_materno_cliente` VARCHAR(45) NULL,
  `codigo_postal` INT NULL,
  `calle` VARCHAR(255) NULL,
  `numero_exterior` VARCHAR(50) NULL,
  `numero_interior` VARCHAR(50) NULL,
  `entre_calles` VARCHAR(512) NULL,
  `referencias` VARCHAR(255) NULL,
  `id_estado` INT NULL,
  `id_municipio` INT NULL,
  `colonia` VARCHAR(255) NULL,
  `nombre_contacto` VARCHAR(255) NULL,
  `telefono` BIGINT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_PV_CLIENTE_PV_ESTADO`
    FOREIGN KEY (`id_estado`)
    REFERENCES `furniture`.`PV_ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_CLIENTE_PV_MUNICIPIO`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `furniture`.`PV_MUNICIPIO` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nom_user` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `id_categoria` INT NOT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_PV_USUARIO_PV_CATEGORIA_USUARIO_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_PV_USUARIO_PV_CATEGORIA_USUARIO`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `furniture`.`PV_CATEGORIA_USUARIO` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_USUARIO_PV_CLIENTE`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `furniture`.`PV_CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_PROCESO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_PROCESO` (
  `id_proceso` INT NOT NULL AUTO_INCREMENT,
  `proceso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_VENTA` (
  `folio` INT NOT NULL AUTO_INCREMENT,
  `feha` DATE NULL,
  `monto` FLOAT NULL,
  `id_cliente` INT NOT NULL,
  `id_proceso` INT NOT NULL,
  PRIMARY KEY (`folio`),
  INDEX `fk_PV_VENTA_PV_CLIENTE1_idx` (`id_cliente` ASC),
  INDEX `fk_PV_VENTA_PV_PROCESO1_idx` (`id_proceso` ASC),
  CONSTRAINT `fk_PV_VENTA_PV_CLIENTE1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `furniture`.`PV_CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_VENTA_PV_PROCESO1`
    FOREIGN KEY (`id_proceso`)
    REFERENCES `furniture`.`PV_PROCESO` (`id_proceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_CATEGORIA` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_ESTADO` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_MUNICIPIO` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_municipio`),
  INDEX `fk_PV_MUNICIPIO_PV_ESTADO1_idx` (`id_estado` ASC),
  CONSTRAINT `fk_PV_MUNICIPIO_PV_ESTADO1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `furniture`.`PV_ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_COLONIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_COLONIA` (
  `id_colonia` INT NOT NULL AUTO_INCREMENT,
  `colonia` VARCHAR(45) NULL,
  `id_municipio` INT NOT NULL,
  PRIMARY KEY (`id_colonia`),
  INDEX `fk_PV_COLONIA_PV_MUNICIPIO1_idx` (`id_municipio` ASC),
  CONSTRAINT `fk_PV_COLONIA_PV_MUNICIPIO1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `furniture`.`PV_MUNICIPIO` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_CP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_CP` (
  `id_cp` INT NOT NULL AUTO_INCREMENT,
  `cp` INT NULL,
  `id_colonia` INT NOT NULL,
  PRIMARY KEY (`id_cp`),
  INDEX `fk_PV_CP_PV_COLONIA1_idx` (`id_colonia` ASC),
  CONSTRAINT `fk_PV_CP_PV_COLONIA1`
    FOREIGN KEY (`id_colonia`)
    REFERENCES `furniture`.`PV_COLONIA` (`id_colonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_PROVEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_PROVEDOR` (
  `id_provedor` INT NOT NULL AUTO_INCREMENT,
  `provedor` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  `correo` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `no_exterior` INT NULL,
  `no_interior` INT NULL,
  `id_estado` INT NOT NULL,
  `id_municipio` INT NOT NULL,
  `id_colonia` INT NOT NULL,
  `id_cp` INT NOT NULL,
  PRIMARY KEY (`id_provedor`),
  INDEX `fk_PV_PROVEDOR_PV_ESTADO1_idx` (`id_estado` ASC),
  INDEX `fk_PV_PROVEDOR_PV_MUNICIPIO1_idx` (`id_municipio` ASC),
  INDEX `fk_PV_PROVEDOR_PV_COLONIA1_idx` (`id_colonia` ASC),
  INDEX `fk_PV_PROVEDOR_PV_CP1_idx` (`id_cp` ASC),
  CONSTRAINT `fk_PV_PROVEDOR_PV_ESTADO1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `furniture`.`PV_ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_PROVEDOR_PV_MUNICIPIO1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `furniture`.`PV_MUNICIPIO` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_PROVEDOR_PV_COLONIA1`
    FOREIGN KEY (`id_colonia`)
    REFERENCES `furniture`.`PV_COLONIA` (`id_colonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_PROVEDOR_PV_CP1`
    FOREIGN KEY (`id_cp`)
    REFERENCES `furniture`.`PV_CP` (`id_cp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_PRODUCTO` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NULL,
  `precio_compra` FLOAT NULL,
  `precio_venta` FLOAT NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_categoria` INT NOT NULL,
  `id_provedor` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_PV_PRODUCTO_PV_CATEGORIA1_idx` (`id_categoria` ASC),
  INDEX `fk_PV_PRODUCTO_PV_PROVEDOR1_idx` (`id_provedor` ASC),
  CONSTRAINT `fk_PV_PRODUCTO_PV_CATEGORIA1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `furniture`.`PV_CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_PRODUCTO_PV_PROVEDOR1`
    FOREIGN KEY (`id_provedor`)
    REFERENCES `furniture`.`PV_PROVEDOR` (`id_provedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_DETALLE_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_DETALLE_VENTA` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `precio_venta` FLOAT NULL,
  `cantidad` INT NULL,
  `folio` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_PV_DETALLE_VENTA_PV_VENTA1_idx` (`folio` ASC),
  INDEX `fk_PV_DETALLE_VENTA_PV_PRODUCTO1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_PV_DETALLE_VENTA_PV_VENTA1`
    FOREIGN KEY (`folio`)
    REFERENCES `furniture`.`PV_VENTA` (`folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PV_DETALLE_VENTA_PV_PRODUCTO1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `furniture`.`PV_PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `furniture`.`PV_IMAGEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `furniture`.`PV_IMAGEN` (
  `id_imagen` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(300) NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `fk_PV_IMAGEN_PV_PRODUCTO1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_PV_IMAGEN_PV_PRODUCTO1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `furniture`.`PV_PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Datos
-- -----------------------------------------------------
insert into pv_categoria_usuario (categoria) values ('administrador');
insert into pv_categoria_usuario (categoria) values ('cliente');
insert into pv_categoria_usuario (categoria) values ('secretaria');
insert into pv_usuario (nom_user,password,id_categoria, email) values ('admin','maNFFVN3iSshg',1, 'admin@furniture.com');
